services:

  django:
    env_file:
      - .devcontainer/.env.local
    restart: "no"
    volumes:
      - ./.devcontainer/_gitignore:/usr/src/geonode/.gitignore
      - ./.devcontainer/_vscode:/usr/src/geonode/.vscode
    ports:
      - "8001:8001"
    command: sleep infinity

  celery:
    env_file:
      - .devcontainer/.env.local
    restart: "no"
    depends_on:
      - django

  geonode:
    env_file:
      - .devcontainer/.env.local
    environment:
      - HTTPS_HOST=
    ports:
      - "80:80"

  geoserver:
    env_file:
      - .devcontainer/.env.local
    build:
      context: ./.devcontainer/docker/geoserver
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE_VERSION=${GEOSERVER_BASE_IMAGE_VERSION}
    environment:
      - OAUTH2_CLIENT_ID=${OAUTH2_CLIENT_ID}
      - OAUTH2_CLIENT_SECRET=${OAUTH2_CLIENT_SECRET}
    ports:
      - "8080:8080"

  db:
    build:
      context: ./.devcontainer/docker/postgresql
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE_VERSION=${POSTGRES_BASE_IMAGE_VERSION}
    ports:
     - "5432:5432"

  mail:
    image: marcopas/docker-mailslurper:latest
    volumes:
      - ./.devcontainer/docker/mail/custom-config.json:/opt/mailslurper/config.json
    ports:
      - "8008:8080"
      - "8085:8085"
    command: "./mailslurper -loglevel debug -logformat simple"
